version: "3.7"

services:
  db:
    image: postgres:15
    container_name: database
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database-volume:/var/lib/postgresql/data

  server:
    build:
      context: .
    container_name: server
    restart: on-failure
    env_file:
      - ".env"
    environment:
      - WAIT_HOSTS=${DATABASE_HOST}:${POSTGRES_PORT}
      - WAIT_SLEEP_INTERVAL=3
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

volumes:
  database-volume:
